### PR TITLE
Add SwordDrill

### PR DESCRIPTION
**Pull request by meichthys**
If this should be added to a separate category other than "Bible", please let me know. The program isn't a "Bible" per-se but displays Bible verses.

### CODE REVIEW

**Review by mattrob33 — CHANGES_REQUESTED** [review]
Sword Drill looks like a cool project! I'm happy to approve adding it.

Can you remove the commit adding a Church Presentation category? It belongs in a separate PR, and I'm not sure that we need that category, especially since we don't have any projects for it yet.

**Comment by meichthys** [comment]
Oops. I thought i removed the Church Presentation category before I submitted the pull request. I'll see if i can get it removed.

**Comment by meichthys** [comment]
I'm not great with git so i wasn't able to 'remove' the `Church Presentation` category, but i did revert the change. 
If you want to keep the commit history clean, I can close this pull request and re-submit it.

**Comment by mattrob33** [comment]
Ah no worries! I'd like to keep discussion open on the Church Presentation category, since it seems potentially useful, so let's separate those out.

I'm not great with git either, but I use it on a daily basis so I've managed to gain some familiarity with it. Try this:

```
git reset --hard HEAD^
git branch add-church-presentation
git reset --hard HEAD^
git push origin main --force
git switch add-church-presentation
git push origin add-church-presentation
```

This will move the commit to add a new category to a new branch called `add-church-presentation`. From there you can open a separate PR from each of those branches (one to add Sword Drill, and one to add the new category).

To explain the git commands above:

`git reset --hard HEAD^` removes your most recent commit from the current branch. So the first `git reset --hard HEAD^` will remove the commit that deleted the church presentation category.

`git branch add-church-presentation` will create a new branch from the current HEAD (which is now "Add church presentation category"). Unlike `git checkout -b` though, this _does not_ switch to that branch, so you are still on the main branch (or whatever branch you started on).

`git reset --hard HEAD^` removes the most recent commit ("Add church presentation category") from the current branch. So now your main branch will be at "Add Sword Drill"

`git push origin main -- force` does a force push of the changes to GitHub. Since you used reset to modify the history, you'll have to add the `--force` flag for your push to succeed.

`git switch add-church-presentation` will switch to your new branch

`git push origin add-church-presentation` will push your new branch. You should now have the `add-church-presentation` branch in GitHub and can open a new PR for it.

Let me know if you have any questions about that or about the PRs!

**Comment by meichthys** [comment]
Wow, that explanation was awesome. It was very clear and concise. Thank You! 
We should be good to go on this pull request. I'll submit the other for "Church Presentation" as i have a project to add there :)

**Review by mattrob33 — APPROVED** [review]
Thanks for taking the time to separate these out, and thanks for adding your project!

**Pull request merged**
