### PR TITLE
Add church presentation category

### PR DESCRIPTION
**Pull request by meichthys**
Project(s) for this category will be submitted in short order.

### CODE REVIEW

**Comment by meichthys** [comment]
It looks like the changes from #4 are still here. If you merge #4 first, will this pull request update accordingly?

**Comment by mattrob33** [comment]
I expect it should merge without issue, but I've had problems with GitHub mergers before. Best practice would be to pull changes from the remote `main` to your local `main`, rebase your `add-church-presentation` branch on top of `main` and then force-push `add-church-presentation` to remote.

Honestly I usually do this with the graphical tools inside IntelliJ so I don't remember the CLI syntax off the top of my head. I can Google it later and comment it for you though if you aren't familiar with it, so you can learn how to do it. It's a pretty important building block of working in a shared codebase.

**Comment by meichthys** [comment]
I think it looks good now 👍
I always get confused when it comes to rebasing. I never know which way to rebase, but i think it makes sense now. I am taking my branch and 'basing' it off of another branch/commit.

**Comment by meichthys** [comment]
@mattrob33 Could you take a look at this PR when you get a chance? No huge rush, just wanted to make sure you saw the changes.

**Comment by mattrob33** [comment]
Do you have projects in mind that will use this category? If so, I'm good adding it. I just don't want to add a category we aren't going to use.

**Comment by meichthys** [comment]
Yes, i have one right now: [OpenLP](https://openlp.org/)

**Pull request merged**
